import type { Command, Option } from 'commander';

/**
 * Renders the complete command reference from the program itself.
 *
 * Generated rather than written, because a hand maintained list of 30-odd
 * commands and every option each one takes is wrong within a release: adding an
 * option is one line, and remembering to mirror it in a table is a separate
 * act nobody performs. `npm run docs` rewrites the page and a test fails when
 * the checked-in copy no longer matches.
 *
 * The prose pages stay hand written — this one is only the exhaustive list.
 */

const HEADER = `<!--
  Generated by "npm run docs" from the command definitions.
  Do not edit by hand: cli/src/docs/reference.ts renders it, and a test fails
  when this file and the program disagree.

  For what the commands are *for*, start at README.md in this directory. This
  page is the exhaustive list of every command, argument and option.
-->

# Command reference

Every command, argument and option, taken straight from the program. For what
each command is _for_, and for worked examples, see the pages it links to:
[Sync](sync.md), [Search](search.md), [Insights](insights.md),
[Digest](digest.md), [Cross links](links.md), [Audit](audit.md),
[Web viewer](web.md) and [MCP server](mcp.md).
`;

export function renderCliReference(program: Command): string {
  const sections: string[] = [HEADER.trimStart()];

  sections.push('```\n' + usage(program, []) + '\n```\n');
  sections.push(globalOptions(program));
  sections.push(contents(program));

  for (const command of program.commands) {
    sections.push(renderCommand(command, [program.name()]));
  }

  return `${sections.join('\n').trimEnd()}\n`;
}

function usage(command: Command, path: string[]): string {
  const name = [...path, command.name()].join(' ');
  const parts = [name];
  if (command.options.length > 0) parts.push('[options]');
  if (command.commands.length > 0) parts.push('<command>');
  for (const argument of command.registeredArguments) {
    const label = argument.variadic ? `${argument.name()}...` : argument.name();
    parts.push(argument.required ? `<${label}>` : `[${label}]`);
  }
  return parts.join(' ');
}

function globalOptions(program: Command): string {
  const rows = program.options.map((option) => row(option));
  return ['## Global options', '', ...table(rows), ''].join('\n');
}

/** A short index, because the page is long by design. */
function contents(program: Command): string {
  const lines = ['## Commands', ''];
  for (const command of program.commands) {
    const names = [command.name(), ...command.aliases()].map((name) => `\`${name}\``).join(', ');
    lines.push(`- [${names}](#${anchor(command.name())}) — ${command.description()}`);
    for (const sub of command.commands) {
      const subNames = [sub.name(), ...sub.aliases()].map((name) => `\`${name}\``).join(', ');
      lines.push(
        `  - [${subNames}](#${anchor(`${command.name()} ${sub.name()}`)}) — ${sub.description()}`,
      );
    }
  }
  lines.push('');
  return lines.join('\n');
}

function anchor(title: string): string {
  return `devcontext-${title}`.toLowerCase().replaceAll(' ', '-');
}

function renderCommand(command: Command, path: string[]): string {
  const full = [...path.slice(1), command.name()].join(' ');
  const depth = path.length; // top level commands are `##`
  const lines: string[] = [];

  lines.push(`${'#'.repeat(Math.min(6, depth + 1))} \`devcontext ${full}\``);
  lines.push('');

  if (command.aliases().length > 0) {
    const aliases = command
      .aliases()
      .map((alias) => `\`${alias}\``)
      .join(', ');
    lines.push(`Alias${command.aliases().length > 1 ? 'es' : ''}: ${aliases}`);
    lines.push('');
  }

  if (command.description() !== '') {
    lines.push(capitalise(command.description()));
    lines.push('');
  }

  lines.push('```');
  lines.push(usage(command, path));
  lines.push('```');
  lines.push('');

  if (command.registeredArguments.length > 0) {
    lines.push('| Argument | Required | Description |');
    lines.push('| -------- | -------- | ----------- |');
    for (const argument of command.registeredArguments) {
      const name = argument.variadic ? `${argument.name()}...` : argument.name();
      lines.push(
        `| \`${name}\` | ${argument.required ? 'yes' : 'no'} | ${cell(argument.description)} |`,
      );
    }
    lines.push('');
  }

  if (command.options.length > 0) {
    lines.push(...table(command.options.map((option) => row(option))));
    lines.push('');
  }

  for (const sub of command.commands) {
    lines.push(renderCommand(sub, [...path, command.name()]));
  }

  return lines.join('\n');
}

interface Row {
  flags: string;
  choices: string;
  fallback: string;
  description: string;
}

function row(option: Option): Row {
  const choices = option.argChoices ? option.argChoices.map((c) => `\`${c}\``).join(', ') : '';
  const fallback =
    option.defaultValue === undefined ||
    option.defaultValue === false ||
    (Array.isArray(option.defaultValue) && option.defaultValue.length === 0)
      ? ''
      : `\`${String(option.defaultValue)}\``;
  return {
    flags: `\`${option.flags}\``,
    choices,
    fallback,
    description: cell(option.description),
  };
}

function table(rows: Row[]): string[] {
  const anyChoices = rows.some((r) => r.choices !== '');
  const anyDefault = rows.some((r) => r.fallback !== '');

  const header = ['Option', ...(anyChoices ? ['Values'] : []), ...(anyDefault ? ['Default'] : [])];
  header.push('Description');

  const lines = [`| ${header.join(' | ')} |`, `| ${header.map(() => '---').join(' | ')} |`];
  for (const r of rows) {
    const cells = [r.flags];
    if (anyChoices) cells.push(r.choices || '—');
    if (anyDefault) cells.push(r.fallback || '—');
    cells.push(r.description);
    lines.push(`| ${cells.join(' | ')} |`);
  }
  return lines;
}

/** Escapes what would otherwise break out of a markdown table cell. */
function cell(text: string | undefined): string {
  return (text ?? '').replaceAll('|', '\\|').replaceAll('\n', ' ');
}

function capitalise(text: string): string {
  return text.charAt(0).toUpperCase() + text.slice(1);
}
